export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as Artists } from './Artists'
export { default as Albums } from './Albums'
export { default as Tools } from './Tools'
export { default as NineWays } from './NineWays'
export { default as FinalCTA } from './FinalCTA'
